=== gabriellawang/ei-project/Integration Middleware v7/new_order.xsd
<?xml version="1.0" encoding="UTF-8"?>

<!-- Created with Liquid XML 2015 Developer Bundle Edition (Education) 13.2.3.6018 (http://www.liquid-technologies.com) -->
<xs:schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	 xmlns:xs="http://www.w3.org/2001/XMLSchema"
	 elementFormDefault="qualified"
	 attributeFormDefault="unqualified">
	<xs:element name="order">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="orderid" type="xs:string" minOccurs="0"/>
				<xs:element name="totalPrice" type="xs:decimal" minOccurs="0"/>
				<xs:element name="timestamp" type="xs:string" minOccurs="0"/>
				<xs:element name="username" type="xs:string" minOccurs="0"/>
				<xs:element name="email" type="xs:string" minOccurs="0"/>
				<xs:element name="phone" type="xs:string" minOccurs="0"/>
				<xs:element name="address" type="xs:string" minOccurs="0"/>
				<xs:element name="postcode" type="xs:unsignedInt" minOccurs="0"/>
				<xs:element name="region" type="xs:string" minOccurs="0"/>
				<xs:element name="storeName" type="xs:string" minOccurs="0"/>
				<xs:element name="package" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="name" type="xs:string" minOccurs="0"/>
							<xs:element name="description" type="xs:string" minOccurs="0"/>
							<xs:element name="price" type="xs:decimal" minOccurs="0"/>
							<xs:element name="qty" type="xs:unsignedByte" minOccurs="0"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== gabriellawang/ei-project/Integration Middleware v7/orders/new_order.xml
<?xml version = "1.0" encoding = "UTF-8"?>
<!-- Created with Liquid XML 2015 Developer Bundle Edition (Education) 13.2.3.6018 (http://www.liquid-technologies.com) -->
<order xmlns:xsi = "http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation = "new_order.xsd">
    
	<orderid>jason01</orderid>
	<totalPrice>29.5</totalPrice>
	<timestamp>25/03/2016 15:00</timestamp>
	
	<username>jason</username>
    <email>yuan629@msn.com</email>
    <phone>98752805</phone>
	<address>80 Stamford Road</address>
    <postcode>178902</postcode>
	
    <storeName>ven2</storeName>
        <package>
            <name>pkg1</name>
			<description>apple+banana+orange</description>
			<price>5.9</price>
            <qty>5</qty>
        </package>
		
</order>
